### ISSUE TITLE
[React] ConcurrentModificationError

### ISSUE THREAD

**Issue by busslina** [GregoryConrad/rearch-dart#149]
I'm getting an error with this code inside a `RearchConsumer.build` method on the new React port. It works well in the Flutter counterpart

```dart
@override
wlib.ReactNode? build(wlib.ComponentHandle use) {
  final loadingController = use(loadingCapsule);

  use.effect(
    () {
      Timer(const Duration(seconds: 10), () {
        loadingCtrl.off();
      });

      return null;
    },
    [],
  );

  return (div(
    {},
    button(
      {
        'onClick': (_) => loadingCtrl.off(),
      },
      'Button',
    ),
  ));
}
```

It fails after 10 seconds on the `Timer` callback execution.

Have you any idea on why it's happening?

It fails too with `callonce` + (Timer or Future.delayed). It's weird because it works well when triggered by a button click, which should produce an identical outcome as they are equally async...

**Comment by busslina** [comment]
> The only reason I can think of is the absence of Bootstrap logic, so I will create it and test it.

No, bootstrap has nothing about this. It has to be something else.

**Comment by GregoryConrad** [comment]
What’s the stack trace?

**Comment by busslina** [comment]
> What’s the stack trace?

Sorry, I removed it accidentally when editing the message.

```
Uncaught 
Object { Symbol("ConcurrentModificationError.modifiedObject"): {…} }
[collection_patch.dart:574:8](https://pandemic-plandemic.ddns.net/lib/_internal/js_dev_runtime/patch/collection_patch.dart)
next collection_patch.dart:574
dispose impl.dart:63
buildNodesAndDependents node.dart:47
runTransaction rearch.dart:137
runTransaction impl.dart:108
```

**Comment by busslina** [comment]
Video demo:

https://github.com/GregoryConrad/rearch-dart/assets/73592852/22395f93-d21b-4df3-b913-ebd978ca7aee

https://github.com/GregoryConrad/rearch-dart/assets/73592852/eee939c6-437b-4d92-8bfd-874636c0c4da

**Comment by GregoryConrad** [comment]
A dispose function is being registered on the capsule (or maybe a listener/onNextUpdate) while the capsule is being disposed. Can perhaps look into it more later, but if this exact same scenario works over in the flutter package, I’d take a look at your usages of any container listeners or onNextUpdate calls that may add in a dispose listener to a capsule that may be getting disposed

**Comment by busslina** [comment]
Btw I just make private a bunch of Consumer stuff (wich I don't know why tey are public on the Flutter implementation if they can be private):
- container listeners
- dependency disposers
- ...

**Comment by busslina** [comment]
It isn't executing `registerDispose()` when the error happened. The 'red marked' is executed on the first build:
![imagen](https://github.com/GregoryConrad/rearch-dart/assets/73592852/27ab4600-40f9-47e5-a44a-088d2a2f1ae2)

**Comment by busslina** [comment]
Detected two creations when it should be only one, of the top level component:
![imagen](https://github.com/GregoryConrad/rearch-dart/assets/73592852/b1360967-33fe-4ff6-9275-a6c1765b029c)

**Comment by GregoryConrad** [comment]
> which I don't know why they are public on the Flutter implementation if they can be private

id have the check the code to be sure, but I believe that’s because they’re defined on a package or library-private class, I.e. they aren’t apart of the public API anyways

**Comment by GregoryConrad** [comment]
The issue is a call to registerDispose somewhere I believe, being called on a capsule’s (whether user-defined or temporary) disposal

**Comment by busslina** [comment]
I detected something weird caused on the `react` package: https://github.com/Workiva/react-dart/issues/393

**Comment by busslina** [comment]
> id have the check the code to be sure, but I believe that’s because they’re defined on a package or library-private class, I.e. they aren’t apart of the public API anyways

You are right. On the flutter implementation they are on a private class. On the react one, on a public class.

**Comment by busslina** [comment]
I simplified the example to this case test: just one component, one capsule, a button and Timer.
So now you can test it easier by installing and executing `webdev` (see README.md).

**Comment by busslina** [comment]
I'm thinking of doing a `react` form because it seems abandoned. Do you think it worth it? In other words do you our issue can be related to their issue?

**Comment by busslina** [comment]
I tested again with my `react` fork, now I'm able to prevent executing ReArch internals by components created by `react` but not inserted in the Component tree....

But the error isn't there. Every `render` calls `_clearDependencies` like the `flutter_rearch` `build` does, then the error came.
```dart
// Clears the old dependencies (which will be repopulated via WidgetHandle)
_clearDependencies();
```
![imagen](https://github.com/Workiva/react-dart/assets/73592852/d51d256b-6505-4ca8-930d-4ae2bbeb7776)

`componentDidUpdate` is just logging, but not doing anything more. But something that can be weird is that the error seems not happening just in `_clearDependencies`, because as you can see, `componentDidUpdate` appears "in the middle".

When triggered by the button click, the execution flow seems the same, but not failing... :

![imagen](https://github.com/Workiva/react-dart/assets/73592852/9c6deba8-5d86-4a54-bef9-20dcef714615)

**Comment by busslina** [comment]
I think I got what is happening: Flutter lib is calling rebuild async and react lib sync. Gonna try to to async too:

![imagen](https://github.com/GregoryConrad/rearch-dart/assets/73592852/3f94393d-b291-42a5-8752-4788900fa8e0)

**Comment by busslina** [comment]
Solved.

Solution:
- Replace sync `forceUpdate()` call on `Api.rebuild()` by `_markNeedsBuild()` async logic.
- Removing unnecessary `_building` flag.
- Calling `_clearNeedsBuild()` in `componentDidUpdate()` instead of in `render()`
