### ISSUE TITLE
warmupToWidget with CapsuleContainer

### ISSUE THREAD

**Issue by opsb** [GregoryConrad/rearch-dart#175]
warmupToWidget is really helpful for setting up widgets but there doesn't appear to be an equivalent when using CapsuleContainer s directly. When writing tests against the CapsuleContainer (instead of a widget test with RearchBootstrapper) it would be helpful if you could wait on capsules to be ready e.g.

```dart

AppointmentService appointmentService(CapsuleHandle use) {
  final venuesService = use(venuesService);
  final appointmentService = AppointmentService(venuesService);
}

final container = CapsuleContainer();
await container.read(futureVenuesService);
container.read(appointmentService);
```

Currently it's possible using 

```dart
final container = CapsuleContainer();
await container.read(futureVenuesService);
container.onNextUpdate(futureVenuesService, () {
  final appointmentService = container.read(appointmentService);
})
```

but it would be good to have an official way to do it.

**Comment by busslina** [comment]
https://github.com/GregoryConrad/rearch-dart/discussions/125
