### ISSUE TITLE
Capsule Creator

### ISSUE THREAD

**Issue by jtkeyva** [GregoryConrad/rearch-dart#240]
Since you have the Signals-esque wrapper already, it would be nice to have an input and output box that could translate the signals-like syntax into ReArch.

Perhaps even a UI to build them would be interesting. With checkboxes for hydration etc

I understand the value of ReArch, but I am still having a hard time wrapping my head around the API. The signals api and docs do a great job of simplifying for us dummies.

**Comment by GregoryConrad** [comment]
>  it would be nice to have an input and output box that could translate the signals-like syntax into ReArch.

It should just be:
```dart
final mySignal = signal(1234);
final myCapsule = capsule((use) => use.data(1234));

final myFutureSignal = futureSignal(fooBar);
final myFutureCapsule = capsule((use) => use.future(fooBar));

// etc.
```

If you so desire, you can also make extensions on the `capsule` in ReArch to make the conversions more 1 to 1 (although I'm not sure how I feel about this for anything but trivial state):
```dart
final myCapsule = capsule.data(1234);
final myFutureCapsule = capsule.future(fooBar);
// etc.
```

The key with ReArch is to just toss the side effects you want into the capsule itself. So for hydration:
```dart
final myHydratedState = capsule((use) {
  final count = use.data<int?>(null);
  final currentlyPersistedCount = use.hydrate(
    count.value,
    read: () async => throw 'TODO',
    write: (newValue) async => throw 'TODO',
  );
  return (count, currentlyPersistedCount);
});
```

**Comment by jtkeyva** [comment]
thanks for the explainer
