### ISSUE TITLE
Is selectAsync-like Functionality Available in ReArch for Asynchronous Property Updates?

### ISSUE THREAD

**Issue by thize** [GregoryConrad/rearch-dart#252]
In Riverpod, the selectAsync method allows for efficient listening to specific properties of asynchronous providers, enabling widgets to rebuild only when the selected property changes. 

 Is there an equivalent approach in ReArch to achieve similar functionality within a capsule? 
 
 Specifically, is it possible to perform a selection on an AsyncValue capsule to update only a particular property asynchronously? 
 
 Any guidance on implementing this pattern in ReArch would be greatly appreciated.

**Comment by GregoryConrad** [comment]
Hey! 👋 

depending on your needs, you could use a combination of:
- `use(someCapsule.map((data) async => throw “todo”))`
- `use.future(futureFromAbove);`
- You can also `.map()` the `AsyncValue` capsule itself to get the data out of it and avoid needing anymore `async`

normally, it is best to just make another capsule instead of using `.map()`, but it’s acceptable in a widget when you just want to get a filter accomplished quickly and/or it relies upon some ephemeral state (like a button toggle).

> Specifically, is it possible to perform a selection on an AsyncValue capsule to update only a particular property asynchronously?

could you provide the specific capsules you have in mind and what you want out of them in your widget? That’d help me provide a clear example of what I’d recommend in your scenario

**Comment by thize** [comment]
Hey again! 👋

Thanks for the clarification earlier. My question is a bit simpler, and it's about **sync capsules** instead of async ones. How can I make the widget rebuild only when a specific property changes in a sync capsule?

Here's a simplified example of my code:

```dart
class MyHomePage extends RearchConsumer {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context, WidgetHandle use) {
    final gems = use(ExampleSync.gemsCapsuleState);
    // final (profile, setProfile) = use(ExampleSync.getProfileCapsuleState);
    print("MyHomePage rearch build");
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: [
            Text("gems: $gems"),
            ElevatedButton(
              onPressed: () {
                print("Add Gems");
                final ccp = CapsuleContainerProvider.containerOf(context);
                final (profile, setProfile) = ccp.read(
                  ExampleSync.getProfileCapsuleState,
                );
                setProfile(
                  UserProfile(coins: profile.coins, gems: profile.gems + 1),
                );
              },
              child: const Text("Add gems"),
            ),
            ElevatedButton(
              onPressed: () {
                print("Add coins");
                final ccp = CapsuleContainerProvider.containerOf(context);
                final (profile, setProfile) = ccp.read(
                  ExampleSync.getProfileCapsuleState,
                );
                setProfile(
                  UserProfile(coins: profile.coins + 1, gems: profile.gems),
                );
              },
              child: const Text("Add Coins"),
            ),
          ],
        ),
      ),
    );
  }
}

class UserProfile {
  const UserProfile({this.gems = 0, this.coins = 0});
  final int coins;
  final int gems;
}

class ExampleSync {
  static (UserProfile, void Function(UserProfile)) getProfileCapsuleState(
    CapsuleHandle use,
  ) {
    return use.state(UserProfile());
  }

  static (UserProfile Function(), void Function(UserProfile))
  getProfileCapsuleData(CapsuleHandle use) {
    return use.data(UserProfile());
  }

  static int gemsCapsuleState(CapsuleHandle use) {
    final gems = use(getProfileCapsuleState.map((profile) => profile.$1.gems));
    return gems;
  }

  static int gemsCapsuleData(CapsuleHandle use) {
    final gems = use(getProfileCapsuleData.map((profile) => profile.$1().gems));
    return gems;
  }
}

class ExampleAsync {
  static (AsyncValue<UserProfile>, void Function())
  getProfileCapsuleRefreshable(CapsuleHandle use) {
    return use.refreshableFuture(() async {
      await Future.delayed(const Duration(seconds: 1));
      return UserProfile();
    });
  }

  static Future<UserProfile> getProfileCapsuleFuture(CapsuleHandle use) async {
    return UserProfile();
  }

  static AsyncValue<UserProfile> getProfileCapsuleAsyncValueFromFuture(
    CapsuleHandle use,
  ) {
    final profile = use(getProfileCapsuleFuture);
    return use.future(profile);
  }

  static AsyncValue<int> gemsCapsule(CapsuleHandle use) {
    final gems = use(
      getProfileCapsuleFuture.map((profile) async => (await profile).gems),
    );
    return use.future(gems);
  }
}
```

In the example above, I want the widget to rebuild **only when `gems` changes**. Currently, it seems like the widget rebuilds whenever `UserProfile` changes, regardless of which property is updated.

How can I filter the rebuild so that it only happens when the `gems` property changes? Any guidance would be much appreciated! 😊

**Comment by GregoryConrad** [comment]
> ```dart
> static int gemsCapsuleState(CapsuleHandle use) {
>   final gems = use(getProfileCapsuleState.map((profile) => profile.$1.gems));
>   return gems;
> }
> static int gemsCapsuleData(CapsuleHandle use) {
>   final gems = use(getProfileCapsuleData.map((profile) => profile.$1().gems));
>   return gems;
> }
> ```

This shouldn't impact rebuild frequency, but you should just be doing:
```dart
static int gemsCapsuleData(CapsuleHandle use) {
  return use(getProfileCapsuleData).value.gems;
}
```
ReArch has builtin build optimizations that stop downstream rebuilds when a capsule's data doesn't change (e.g. `capsuleOldData == capsuleNewData`). `.map()` should only be used from within a Widget, when you can't rely upon this optimization as easily/if at all.

Also, I'm guessing you created both the data/state capsules just to test what was going on, but I'd recommend just using the newer `use.data` side effect unless you explicitly want the API provided by `use.state`.

> Currently, it seems like the widget rebuilds whenever UserProfile changes, regardless of which property is updated.

You often can minimize rebuilds by splitting up your state into smaller capsules (so perhaps 2 individual capsules for the gems and another for the coins, and perhaps another two for setters/incrementors). But, in your case, this was really an XY problem: you need to limit the scope at which you're introducing the capsules (often easiest through a `RearchBuilder`). When you `use(someCapsule)`, the `RearchConsumer` that provides you with that `use` will rebuild whenever the capsules it's `use`-ing rebuild and produce new data. Thus, you need to introduce those capsules further down the Widget tree.

```dart
// This is written with the new, recently-stabilized capsule() syntax.
// Feel free to continue using the original syntax if you prefer it;
// it is 100% interoperable/no difference in functionality.

final Capsule<ValueWrapper<UserProfile>> userProfileManager =
  capsule((use) => use.lazyData(UserProfile.new));

final Capsule<int> userGemsCapsule = capsule((use) => use(userProfileManager).value.gems);

// https://rearch.gsconrad.com/paradigms/actions
final Capsule<void Function()> incrementUserGemsAction = capsule((use) {
  final userProfile = use(userProfileManager);
  return () {
    userProfile.value = UserProfile(
      coins: userProfile.value.coins,
      gems: userProfile.value.gems + 1,
    );
  };
});

class MyHomePage extends RearchConsumer {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context, WidgetHandle use) {
    final gems = use(userGemsCapsule);
    // The following could also be acceptable, but I'd prefer the explicit capsule above:
    // final gems = use(userProfileManager.map((profile) => profile.value.gems));

    print("MyHomePage building...");
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: [
            Text("gems: $gems"),
            RearchBuilder(
              builder: (context, use) {
                final incrementGems = use(incrementUserGemsAction);
                return ElevatedButton(
                  onPressed: incrementGems,
                  child: const Text("Add gems"),
                );
              },
            ),
          ],
        ),
      ),
    );
  }
}
```
