### ISSUE TITLE
[Example App] Online API wrapper, e.g. a weather app

### ISSUE THREAD

**Issue by TC3000** [GregoryConrad/rearch-dart#73]
May you please add more examples? Perhaps a simple weather app demonstrating:
* making API calls.
* unit tests.
* recommended project structure (folders, naming conventions, etc).

Have a look at this great example:
https://github.com/felangel/bloc/tree/master/examples/flutter_weather

**Comment by GregoryConrad** [comment]
Hi! 👋

I've got another example app on the back burner (#70), but I could also do a quick API wrapper/a weather app.

Just wanted to touch on this briefly:

> recommended project structure (folders, naming conventions, etc).

Aside from _capsule_ naming conventions (`xyzCapsule`, `xyzManager`, `xyzFactory`, `xyzAction`, `xyzAsyncCapsule`, and maybe another one or two I'm forgetting that are in the [documentation](https://rearch.gsconrad.com)), ReArch is unopinionated with how you structure your code (see #28 for more). Thus, I may take a particular approach in my code, but that doesn't mean I'd recommend everyone use that for their applications.

**Comment by GregoryConrad** [comment]
I'll treat this issue as a tracking issue for an API wrapper sort of app (I'll probably stick with a weather app per your suggestion).

**Comment by GregoryConrad** [comment]
Lmk if you have any questions about https://github.com/GregoryConrad/rearch-dart/tree/main/examples/weather_app!
