### ISSUE TITLE
TODO Example Not Working on Web

### ISSUE THREAD

**Issue by jtkeyva** [GregoryConrad/rearch-dart#98]
The TODO example is not working on Flutter Web.

Also in chrome it shows:
<img width="1089" alt="image" src="https://github.com/GregoryConrad/rearch-dart/assets/2954865/6c7b616c-34a3-40b8-98a2-b886c9747324">

```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during layout:
A RenderFlex overflowed by 798 pixels on the bottom.

The relevant error-causing widget was:
  Column
```

Also, do you have a reccomended way to "Arch"itect? The demo is a lot of lines of code. Do you reccomend splitting up functions and state into different files? Like in BLoC I have todo_page.dart todo_state.dart and todo_cubit.dart. What do you recommend?

**Comment by GregoryConrad** [comment]
The TODOs example doesn’t work on web, but should on any other platform (designed for mobile though). It’s also all in one file intentionally so that the “Example” tab on the pub.dev listing has the full example source code.

**Comment by jtkeyva** [comment]
Got it. As an end user, I would expect the example to work on all platforms that you support. Also, maybe not depend on any other packages as well and keep the focus purely on ReArch. Just saying that I expect to fire up the example and only be learning about the ReArch package, not Mimir.
